# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whichLessDVPresence <- function(value, prob) {
    .Call('_ldacov_whichLessDVPresence', PACKAGE = 'ldacov', value, prob)
}

ldmultinom <- function(x, size, lprob) {
    .Call('_ldacov_ldmultinom', PACKAGE = 'ldacov', x, size, lprob)
}

LogLikMultin <- function(nloc, ncomm, nspp, LogPhi, Arraylsk) {
    .Call('_ldacov_LogLikMultin', PACKAGE = 'ldacov', nloc, ncomm, nspp, LogPhi, Arraylsk)
}

SampleArray <- function(Arraylsk, nloc, nspp, ncomm, NBN, y, LogPhi, LogOneMinusP, runif1, nlk) {
    .Call('_ldacov_SampleArray', PACKAGE = 'ldacov', Arraylsk, nloc, nspp, ncomm, NBN, y, LogPhi, LogOneMinusP, runif1, nlk)
}

rmultinom1 <- function(runif1, prob, ncommun) {
    .Call('_ldacov_rmultinom1', PACKAGE = 'ldacov', runif1, prob, ncommun)
}

#' This function samples z's
samplez <- function(theta, phi, y, ncommun, nloc, nspp, zeroes) {
    .Call('_ldacov_samplez', PACKAGE = 'ldacov', theta, phi, y, ncommun, nloc, nspp, zeroes)
}

#' This function converts vmat into theta
convertVtoTheta <- function(vmat, prod) {
    .Call('_ldacov_convertVtoTheta', PACKAGE = 'ldacov', vmat, prod)
}

#' This function calculates ngreater
ngreater <- function(nlk, nloc, ncommun) {
    .Call('_ldacov_ngreater', PACKAGE = 'ldacov', nlk, nloc, ncommun)
}

LogTargetNBN <- function(Media, y, NBN) {
    .Call('_ldacov_LogTargetNBN', PACKAGE = 'ldacov', Media, y, NBN)
}

DoublingNBN <- function(yslice, w, y, NBN, Media, MaxIter, LoThresh) {
    .Call('_ldacov_DoublingNBN', PACKAGE = 'ldacov', yslice, w, y, NBN, Media, MaxIter, LoThresh)
}

ShrinkAndSample <- function(Media, rango1, yslice, y, NBN, MaxIter, LoThresh) {
    .Call('_ldacov_ShrinkAndSample', PACKAGE = 'ldacov', Media, rango1, yslice, y, NBN, MaxIter, LoThresh)
}

SampleNBN <- function(Media, y, NBN, w, MaxIter, LoThresh) {
    .Call('_ldacov_SampleNBN', PACKAGE = 'ldacov', Media, y, NBN, w, MaxIter, LoThresh)
}

LogTargetBetas <- function(LogMediaMiss, param, y, xmat, target, var1, NBN, LgammaNBN) {
    .Call('_ldacov_LogTargetBetas', PACKAGE = 'ldacov', LogMediaMiss, param, y, xmat, target, var1, NBN, LgammaNBN)
}

DoublingBetas <- function(LogMediaMiss, yslice, w, param, y, xmat, target, var1, NBN, LgammaNBN, MaxIter) {
    .Call('_ldacov_DoublingBetas', PACKAGE = 'ldacov', LogMediaMiss, yslice, w, param, y, xmat, target, var1, NBN, LgammaNBN, MaxIter)
}

SampleEachParamBetas <- function(LogMediaMiss, rango1, yslice, param, y, xmat, target, var1, NBN, MaxIter, LoThresh) {
    .Call('_ldacov_SampleEachParamBetas', PACKAGE = 'ldacov', LogMediaMiss, rango1, yslice, param, y, xmat, target, var1, NBN, MaxIter, LoThresh)
}

MatrixMultip <- function(xmat, param, nparam) {
    .Call('_ldacov_MatrixMultip', PACKAGE = 'ldacov', xmat, param, nparam)
}

SampleBetas <- function(param, y, xmat, w, nparam, ncomm, var1, NBN, MaxIter, LoThresh) {
    .Call('_ldacov_SampleBetas', PACKAGE = 'ldacov', param, y, xmat, w, nparam, ncomm, var1, NBN, MaxIter, LoThresh)
}

